version: '3.7'

networks:
  laravel:

volumes:
  mysql-data:

# Laravel foundation config
x-laravel: &laravel-base
  volumes:
    - ./:/var/www
  env_file:
    - .env
    - .docker/php/docker.env
  networks:
    - laravel

services:
  # Main application
  application:
    << : *laravel-base
    image: docker.pkg.github.com/autosiero/docker-laravel/php-apache
    build:
      context: .docker/php
      target: apache
    ports:
      - 127.0.0.1:8080:80

  # Job runner
  horizon:
    << : *laravel-base
    image: docker.pkg.github.com/autosiero/docker-laravel/php-horizon
    build:
      context: .docker/php
      target: horizon

  # MySQL database
  database:
    image: docker.pkg.github.com/autosiero/docker-laravel/database
    build:
      context: .docker/mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_ONETIME_PASSWORD: 'true'
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - 127.0.0.1:8006:3306
    networks:
      - laravel

  # Redis
  redis:
    image: redis:alpine
    networks:
      - laravel
    ports:
      - 127.0.0.1:13379:6379

  # PhpMyAdmin
  pma:
    image: docker.pkg.github.com/autosiero/docker-laravel/php-phpmyadmin
    build:
      context: .docker/phpmyadmin
    networks:
      - laravel
    environment:
      PMA_HOST: database
      PMA_USER: phpmyadmin
      PMA_PASSWORD: phpmyadmin
    depends_on:
      - database

  # Mailhog
  mail:
    image: mailhog/mailhog:latest
    networks:
      - laravel
